import type { TransportApp } from "./project-runtime";

const replacements: Array<[string, string]> = [
  ["التطبيقات محور الصعيد الغربي باللغة الانجليزية", "Western Upper Egypt Axis applications"],
  ["التطبيقات محور الصعيد الغربي باللغة العربية", "Western Upper Egypt Axis applications"],
  ["القوس الشرقى للدائرى الأقليمى و خط الروبيكى باللغة الانجليزية", "Regional Ring Road eastern arc and Robeki railway"],
  ["القوس الشرقى للدائرى الأقليمى و خط الروبيكى", "Regional Ring Road eastern arc and Robeki railway"],
  ["وصلة دهشور الجنوبية", "Dahshur South Link"],
  ["محور كلابشة", "Kalabsha Axis"],
  ["طريق قنا الأقصر", "Qena-Luxor Road"],
  ["محور قنا", "Qena Axis"],
  ["محور قوص", "Qus Axis"],
  ["وصلة طريق السويس من الطريق الدائري", "Suez Ring Road Link"],
  ["طريق القاهرة - السويس الصحراوي", "Cairo-Suez Desert Road"],
  ["السويس الحر", "Suez Free Road"],
  ["محور الضبعة", "El Dabaa Axis"],
  ["كل القطاعات", "All sectors"],
  ["نطاق العرض", "Display extent"],
  ["أبو سمبل", "Abu Simbel"], ["بني سويف", "Beni Suef"], ["أسيوط", "Assiut"], ["أسوان", "Aswan"], ["الجيزة", "Giza"],
  ["المنيا", "Minya"], ["الفيوم", "Fayoum"], ["سوهاج", "Sohag"], ["الأقصر", "Luxor"], ["قنا", "Qena"],
  ["الدراسة المدنية", "Civil study"],
  ["مفتاح استخدامات الأراضي", "Land-use legend"],
  ["استخدامات الأراضي المرجعية", "Reference land use"],
  ["استخدامات الأراضي - سنة البداية", "Land use - start year"],
  ["استخدامات الأراضي - سنة النهاية", "Land use - end year"],
  ["استخدامات الأراضي", "Land use"],
  ["أراضٍ فضاء", "Vacant land"],
  ["خدمات ومرافق", "Services and facilities"],
  ["نقل ومرافق عامة", "Transport and utilities"],
  ["ترفيهي وسياحي", "Recreation and tourism"],
  ["مقابر", "Cemeteries"],
  ["مسطحات مائية", "Water bodies"],
  ["جزر", "Islands"],
  ["طرق", "Roads"],
  ["تعليمي", "Education"],
  ["حكومي", "Government"],
  ["غير مصنف", "Unclassified"],
  ["المباني", "Buildings"],
  ["قطع الأراضي", "Land parcels"],
  ["المعالم والخدمات", "Landmarks and services"],
  ["الرفع الميداني", "Field survey"],
  ["شبكة النقل", "Transport network"],
  ["حدود المحافظات", "Governorate boundaries"],
  ["عدد المعالم الأصلية", "Source feature count"],
  ["كود استخدام الأرض", "Land-use code"],
  ["الهيئة العامة لتخطيط مشروعات النقل", "General Authority for Transport Planning"],
  ["منصة التطبيقات المكانية المتكاملة", "Integrated geospatial applications platform"],
  ["استعراض بيانات القطاع، الخرائط الرقمية، المؤشرات الاقتصادية، الدراسة الميدانية ومرفقات المشروع من واجهة واحدة.", "Explore sector data, digital maps, economic indicators, field studies and project evidence from one workspace."],
  ["طبقات قاعدة البيانات المحلية الخاصة بهذا القطاع فقط.", "Local database layers for this sector only."],
  ["القيم المراجعة من التقرير وطبقات قاعدة البيانات.", "Values verified against the report and local database layers."],
  ["المراجع المرتبطة بالقطاع من تقارير وزارة النقل.", "Sector references from Ministry of Transport reports."],
  ["تطور استخدامات الأراضي قبل وبعد إنشاء المحور", "Land-use development before and after corridor construction"],
  ["تطور استخدامات الأراضي المحيطة بالمحور قبل وبعد الإنشاء", "Development of land uses surrounding the corridor before and after construction"],
  ["تطور استخدامات الأراضي من 2014 حتى 2023", "Land-use development from 2014 to 2023"],
  ["حرّك الفاصل يمينًا ويسارًا للمقارنة بين جانبي الصورة الأصلية الواردة في تقرير القطاع.", "Drag the divider left or right to compare both sides of the original image documented in the sector report."],
  ["خريطة قمر صناعي تفاعلية تعرض حدود الدراسة ومسار الطريق ومناطق التغير العمراني والزراعي للقطاع المحدد فقط. استخدم أزرار التكبير واسحب الخريطة، وانقر على أي عنصر لعرض بياناته الوصفية.", "An interactive satellite map showing the selected sector's study boundary, road alignment, and urban and agricultural change. Use the zoom controls, drag to pan, and select a feature to inspect its attributes."],
  ["يتم عرض البيانات المحلية المراجعة للقطاع.", "Verified local sector data is displayed."],
  ["يتم عرض جميع قطاعات المشروع من قاعدة البيانات المحلية.", "All project sectors are displayed from the local database."],
  ["الصور الأصلية المستخرجة من تقرير القطاع دون استبدالها بصور عامة.", "Original images extracted from the sector report, with no generic replacements."],
  ["لا توجد صورة مقارنة زمنية موثقة لهذا القطاع داخل ملفات التقارير الحالية؛ الخريطة بالأعلى تعرض بياناته المكانية المتاحة دون إضافة صورة افتراضية.", "No documented time-comparison image for this sector exists in the current report files. The map above shows the available spatial data without a fabricated image."],
  ["اختر أحد قطاعات المحور من الشريط العلوي لعرض المقارنة الزمنية الموثقة الخاصة به.", "Select a corridor sector from the top navigation to view its documented time comparison."],
  ["استعرض حدود الدراسة ومسار الطريق ومناطق التغير العمراني والزراعي من البيانات المحلية للقطاع.", "Explore the study boundary, road alignment, and urban and agricultural change from the sector dataset."],
  ["لا توجد صور تقرير لهذا القطاع؛ يتم عرض البيانات المحلية المتاحة فقط.", "No report images are available for this sector; only verified local data is shown."],
  ["يمكنك التكبير والسحب والنقر على أي معلم لعرض بياناته.", "Zoom, pan and select any feature to inspect its attributes."],
  ["اختر نوع البيانات لاستعراض طبقته وسجلاته على خريطة القطاع.", "Choose a data category to display its layer and records on the sector map."],
  ["تصفح تطبيقات القطاع كما في معرض التطبيقات الأصلي، أو اختر طبقة لفحص جميع معالمها على الخريطة التفاعلية.", "Browse sector applications as in the original application gallery, or select a layer to inspect all its features on the interactive map."],
  ["تطبيقات وخرائط القطاع", "Sector applications and maps"],
  ["تطبيقات مرتبطة بهذا القطاع", "applications linked to this sector"],
  ["طبقات قاعدة البيانات", "Database layers"],
  ["اختر طبقة لإظهارها منفردة وفحص بياناتها.", "Select a layer to isolate it and inspect its data."],
  ["عرض تفاصيل التطبيق", "View application details"],
  ["إجمالي مساحة الأراضي الزراعية (فدان)", "Total agricultural land area (feddans)"],
  ["مساحة التغير الزراعي المحصورة (فدان)", "Mapped agricultural change area (feddans)"],
  ["إجمالي مساحة الأراضي العمرانية (كم²)", "Total urban land area (km²)"],
  ["مساحة التغير العمراني المحصورة (كم²)", "Mapped urban change area (km²)"],
  ["إجمالي مساحة الأراضي المتغيرة (كم²)", "Total changed land area (km²)"],
  ["سنة القياس", "Measurement year"],
  ["توزيع مناطق التغير", "Distribution of change areas"],
  ["اضغط على العمود لتصفية طبقة الخريطة", "Select a bar to filter the map layer"],
  ["اضغط لعرض التغير العمراني فقط", "Select to show urban change only"],
  ["تحت الإنشاء", "Under construction"],
  ["إجمالي مساحة التغير بالأراضي الزراعية (فدان)", "Total agricultural land change (feddans)"],
  ["مقارنة مساحات استخدامات الأراضي بين عامي 2014 و2023", "Land-use area comparison: 2014 vs 2023"],
  ["مقارنة مساحات استخدامات الأراضي", "Land-use area comparison"],
  ["نسبة مساحة التغير العمراني من منطقة الدراسة", "Urban change as a share of the study area"],
  ["نسبة التغير العمراني بمنطقة الدراسة", "Urban change within the study area"],
  ["فرص العمل لمشروعات المباني المستحدثة", "Jobs associated with newly developed buildings"],
  ["فرصة عمل تقديرية مرتبطة بمناطق التغير", "Estimated jobs associated with change areas"],
  ["مناطق تغير استخدامات الأراضي", "Land-use change areas"],
  ["التغير السنوي لأسعار الأراضي", "Annual land-price change"],
  ["اضغط على أي نقطة لاستعراض السنة", "Select any point to inspect the year"],
  ["عرض السلسلة على الرسم", "Show series on chart"],
  ["أسعار الأراضي العمرانية", "Urban land prices"],
  ["أسعار الأراضي الزراعية", "Agricultural land prices"],
  ["أسعار الأراضي الصناعية", "Industrial land prices"],
  ["فرق أسعار الأراضي العمرانية", "Urban land price difference"],
  ["فرق أسعار الأراضي الزراعية", "Agricultural land price difference"],
  ["فرق أسعار الأراضي الصناعية", "Industrial land price difference"],
  ["لا توجد قيم أسعار موثقة لهذا القطاع في ملفات التقارير الحالية. اختر «كل القطاعات» أو قطاعًا آخر من قائمة الخريطة.", "No documented price values are available for this sector in the current report files. Select All sectors or another map sector."],
  ["لا توجد سلسلة أسعار موثقة للقطاع المحدد.", "No documented price series is available for the selected sector."],
  ["لا تتوفر مقارنة زمنية منفصلة موثقة لـ", "No separately documented time comparison is available for"],
  ["في ملف التصدير الحالي؛ الخريطة والبطاقات تعرض بيانات القطاع المختار فقط.", "in the current export; the map and cards show only the selected sector's data."],
  ["مساحة منطقة الدراسة (كم²)", "Study area (km²)"],
  ["مساحة منطقة الدراسة", "Study area"],
  ["طول محور الدراسة (كم)", "Corridor length (km)"],
  ["طول محور الدراسة", "Corridor length"],
  ["مساحة التغير العمراني (كم²)", "Urban change area (km²)"],
  ["مساحة التغير العمراني", "Urban change area"],
  ["العمالة الزراعية (بالألف)", "Agricultural employment (thousands)"],
  ["نسب أنواع محاصيل الأراضي الزراعية", "Agricultural crop shares"],
  ["نسب ملكية الأراضي الزراعية", "Agricultural ownership shares"],
  ["مؤشرات الدراسة المدنية", "Civil study indicators"],
  ["عناصر الرفع المدني المسجلة", "Recorded civil-survey features"],
  ["طبقات المشروع المتاحة", "Available project layers"],
  ["العناصر العمرانية", "Urban features"],
  ["العناصر الزراعية", "Agricultural features"],
  ["سيناريو الأثر التنموي حتى 2053", "Development impact scenario through 2053"],
  ["المساحة العمرانية التقديرية", "Estimated urban area"],
  ["فرص العمل المرتبطة بالقطاع", "Sector-related jobs"],
  ["مؤشر التطور الزمني", "Timeline progress"],
  ["منطقة الدراسة ومسار المحور", "Study area and corridor alignment"],
  ["الخريطة التفاعلية للقطاع", "Interactive sector map"],
  ["المقارنة البصرية لأعمال المشروع", "Visual project comparison"],
  ["حرّك المؤشر لمقارنة مرجعي التقرير.", "Move the slider to compare the two report references."],
  ["أعمال ومرفقات القطاع", "Sector work and evidence"],
  ["أعمال ومرفقات المشروع", "Project work and evidence"],
  ["مرفقات المشروع", "Project evidence"],
  ["الخرائط والتطورات", "Maps and developments"],
  ["لوحة المؤشرات", "Indicators dashboard"],
  ["مقدمة", "Introduction"],
  ["الدراسة الميدانية ومرفقات المشروع", "Field study and project evidence"],
  ["مؤشرات الأسعار واستخدامات الأراضي", "Price and land-use indicators"],
  ["منطقة الدراسة والطبقات", "Study area and layers"],
  ["استعراض خريطة القطاع", "Explore sector map"],
  ["قصة مكانية تفاعلية", "Interactive spatial story"],
  ["ابدأ التصفح", "Start exploring"],
  ["بحث في الطبقات", "Search layers"],
  ["اكتب اسم الطبقة", "Enter a layer name"],
  ["قائمة الطبقات", "Layer list"],
  ["خريطة الأساس", "Basemap"],
  ["حدود منطقة الدراسة", "Study-area boundary"],
  ["مسار المحور", "Corridor alignment"],
  ["محور الطريق", "Road alignment"],
  ["التغير العمراني", "Urban change"],
  ["التغير الزراعي", "Agricultural change"],
  ["التغير الصناعي", "Industrial change"],
  ["تغير عمراني", "Urban change"],
  ["تغير زراعي", "Agricultural change"],
  ["تغير صناعي", "Industrial change"],
  ["استخدامات الأراضي 2014", "2014 land use"],
  ["إجمالي مساحة الأراضي الزراعية (فدان)", "Total agricultural land area (feddans)"],
  ["عدد العمالة الزراعية", "Agricultural workforce"],
  ["عدد العمالة الصناعية", "Industrial workforce"],
  ["إجمالي مساحة الأراضي الصناعية (كم²)", "Total industrial land area (km²)"],
  ["نسب أنواع محاصيل الأراضي الزراعية", "Agricultural crop distribution"],
  ["نسب ملكية الأراضي الزراعية", "Agricultural land ownership"],
  ["نسبة التغير بالأراضي الزراعية", "Agricultural land change rate"],
  ["نسبة التغير بالأراضي الصناعية", "Industrial land change rate"],
  ["محاصيل موسمية", "Seasonal crops"],
  ["خضروات", "Vegetables"],
  ["فاكهة", "Fruit"],
  ["ملك", "Owned"],
  ["الأراضي العمرانية", "Urban land"],
  ["الأراضي الزراعية", "Agricultural land"],
  ["الأراضي الصناعية", "Industrial land"],
  ["صور أقمار صناعية", "Satellite imagery"],
  ["صورة قمر صناعي", "satellite tile"],
  ["قمر صناعي", "Satellite imagery"],
  ["عجلة الماوس للتكبير · اسحب لتحريك الخريطة", "Mouse wheel to zoom · drag to pan"],
  ["عرض تفاعلي مترابط", "Linked interactive view"],
  ["إظهار كل البيانات", "Show all data"],
  ["تكبير", "Zoom in"],
  ["تصغير", "Zoom out"],
  ["إغلاق", "Close"],
  ["طبوغرافية", "Topographic"],
  ["داكنة", "Dark"],
  ["بيانات مكانية محلية", "Local spatial data"],
  ["نقطة هندسية", "geometry points"],
  ["طبقات متاحة", "available layers"],
  ["جارٍ تحميل طبقات المشروع المحلية…", "Loading local project layers…"],
  ["جارٍ قراءة أسعار الأراضي من قاعدة بيانات المشروع…", "Loading documented land-price indicators…"],
  ["جارٍ قراءة البيانات…", "Loading data…"],
  ["جارٍ إنشاء الرسم البياني…", "Building chart…"],
  ["جارٍ إنشاء المقارنة…", "Building comparison…"],
  ["لا توجد هندسة مكانية في قاعدة المشروع الحالية", "No sector-matched geometry is available in the current project database"],
  ["بيانات العنصر", "Feature attributes"],
  ["بيانات محلية مترابطة", "Connected local data"],
  ["مؤشرات من التقرير - لا توجد طبقات محلية مطابقة", "Report indicators - no matching local spatial layers"],
  ["صور أقمار صناعية مرجعية · لا توجد هندسة محلية مطابقة للقطاع", "Reference satellite imagery · no matching local sector geometry"],
  ["ملء الشاشة", "Full screen"],
  ["جميع الفئات", "All categories"],
  ["أكبر 4 فئات", "Top 4 categories"],
  ["كل الفئات", "All categories"],
  ["المؤشرات", "Indicators"],
  ["الخريطة التفاعلية", "Interactive map"],
  ["الرئيسية", "Overview"],
  ["أعمال المشروع", "Project work"],
  ["وزارة النقل", "Ministry of Transport"],
  ["اسم القطاع", "Sector name"],
  ["اسم المحافظة", "Governorate"],
  ["اسم المحور", "Corridor name"],
  ["استخدام الأرض", "Land use"],
  ["وصف الاستخدام", "Use description"],
  ["نمط العمران", "Urban pattern"],
  ["نوع طبيعة المنطقة", "Area type"],
  ["نوع ملكية الأرض", "Land ownership type"],
  ["أنواع المحاصيل المزروعة", "Cultivated crop types"],
  ["مساحة المنطقة كم2", "Area (km²)"],
  ["مساحة التغير كم2", "Change area (km²)"],
  ["مساحة التغير بالمتر", "Change area (m²)"],
  ["المساحة فدان", "Area (feddans)"],
  ["المساحة كم2", "Area (km²)"],
  ["طول المحور كم", "Corridor length (km)"],
  ["سعر الأرض 2014", "Land price 2014"],
  ["سعر الأرض 2023", "Land price 2023"],
  ["فرق السعر", "Price difference"],
  ["عدد المبانى", "Building count"],
  ["عدد المنشأت التغير", "Changed structure count"],
  ["نسبة المساحة", "Area share"],
  ["نسبة المساحه", "Area share"],
  ["منطقة الدراسة", "Study area"],
  ["صفحة", "Page"],
  ["قطاع", "Sector"],
  ["عنصر", "feature"],
  ["كم²", "km²"],
  ["كم", "km"],
  ["فدان", "feddan"],
  ["تريليون ج.م", "trillion EGP"],
  ["مليار ج.م", "billion EGP"],
  ["مليون ج.م", "million EGP"],
  ["ج.م", "EGP"],
  ["عمراني", "Urban"],
  ["زراعي", "Agricultural"],
  ["صناعي", "Industrial"],
  ["المحاصيل", "Crops"],
  ["الملكية", "Ownership"],
  ["إيجار", "Lease"],
  ["تمليك", "Ownership"],
  ["قائمة", "Existing"],
];

function translate(value: string): string {
  let result = value;
  for (const [arabic, english] of replacements) result = result.replaceAll(arabic, english);
  return result;
}

function translateNode(node: Node): void {
  if (node.nodeType === Node.TEXT_NODE && node.textContent?.trim()) node.textContent = translate(node.textContent);
  if (node instanceof HTMLElement) {
    for (const name of ["aria-label", "title", "placeholder", "alt"]) {
      const value = node.getAttribute(name);
      if (value) node.setAttribute(name, translate(value));
    }
  }
  node.childNodes.forEach(translateNode);
}

export function enableApplicationLocalization(app: TransportApp, root: HTMLElement): void {
  if (app.language !== "en") return;
  root.classList.add("english-ui");
  translateNode(root);
  const observer = new MutationObserver((mutations) => mutations.forEach((mutation) => mutation.addedNodes.forEach(translateNode)));
  observer.observe(root, { childList: true, subtree: true });
}
