"""Extract reviewed, same-site satellite comparison images from source DOCX reports.

The numeric indexes refer to the embedded-image contact sheets generated by
inspect-documentation-media.py. Keep the source document and index recorded in
the output manifest so every published swipe can be audited.
"""

from pathlib import Path
from zipfile import ZipFile
import json

ROOT = Path(__file__).resolve().parents[1]
SOURCE = ROOT.parents[1] / "التوثيق"
REPORTS = ROOT.parents[1] / "التقارير"
DEST = ROOT / "public" / "references" / "documentation-swipe"
MANIFEST = ROOT / "registry" / "documentation-swipes.json"

# Each pair shows the same outlined site in the earlier and later imagery.
REVIEWED = {
    "regional-ring-road": ("whole_report_01_Intro _ Eklimy_modified2024.docx", [(8, 9)]),
    "dahshur-south-link": ("whole_report_02_ Dahshor_modified2024.docx", [(8, 9), (31, 32)]),
    "suez-ring-link": ("whole_report_03_Suize_modified2024.docx", [(3, 4), (5, 6)]),
    "qena-luxor-road": ("whole_report_04_Qena_modified2024.docx", [(5, 6), (7, 8)]),
    "qus-axis": ("whole_report_05_ Qos_modified2024.docx", [(4, 5), (6, 7)]),
    "kalabsha-axis": ("whole_report_06_Kalabsha_modified2024.docx", [(4, 5), (6, 7)]),
    "cairo-suez-road": ("قطاع_السويس_التقرير_النهائي.docx", [(23, 24), (25, 26), (27, 28), (29, 30)]),
    "dabaa-axis": ("Nakl_Dabaa_30Dec2023.pptx", [(7, 8)]),
    "western-upper-egypt/abu-simbel": ("قطاع_ابو_سمبل-_التقرير_النهائي_-.docx", [(35, 36), (37, 38)]),
    "western-upper-egypt/luxor": ("قطاع_الاقصر-_التقرير_النهائي.docx", [(20, 21), (22, 23), (26, 27), (28, 29)]),
    "western-upper-egypt/qena": ("قطاع_قنا-_التقرير_النهائي.docx", [(20, 21), (22, 23), (26, 27)]),
    "western-upper-egypt/sohag": ("التقرير_قطاع_محافظة_سوهاج.docx", [(5, 6), (7, 8)]),
    "western-upper-egypt/assiut": ("قطاع_أسيوط_التقرير_النهائي.docx", [(20, 21), (23, 24), (27, 28)]),
    "western-upper-egypt/minya": ("قطاع_المنيا_التقرير_النهائي.docx", [(21, 22), (23, 24), (27, 28)]),
    "western-upper-egypt/fayoum": ("قطاع_الفيوم_-_التقرير_النهائي.docx", [(36, 37), (41, 42), (43, 44), (45, 46)]),
    "western-upper-egypt/giza": ("قطاع_الجيزةالتقرير_النهائي_.docx", [(21, 23), (24, 25), (26, 27)]),
    "western-upper-egypt/aswan": ("قطاع_أسوان-_التقرير_النهائي.docx", [(31, 32), (33, 34)]),
    "western-upper-egypt/beni-suef": ("\u0642\u0637\u0627\u0639_\u0628\u0646\u064a_\u0633\u0648\u064a\u0641_\u0627\u0644\u062a\u0642\u0631\u064a\u0631_\u0627\u0644\u0646\u0647\u0627\u0626\u064a.docx", [(22, 23), (24, 25)]),
}

# The reviewed Luxor frames at indexes 21/22 are the same outlined site;
# earlier adjacent frames include a regional overview and are not comparable.
REVIEWED["western-upper-egypt/luxor"] = (REVIEWED["western-upper-egypt/luxor"][0], [(21, 22)])

DEST.mkdir(parents=True, exist_ok=True)
result = {"groups": {}}
for group, (document_name, pairs) in REVIEWED.items():
    document = (REPORTS if document_name.endswith(".pptx") else SOURCE) / document_name
    if not document.is_file():
        raise FileNotFoundError(document)
    with ZipFile(document) as archive:
        images = [name for name in archive.namelist() if name.startswith(("word/media/", "ppt/media/")) and name.lower().endswith((".png", ".jpg", ".jpeg"))]
        reviewed = []
        for pair_number, (before_index, after_index) in enumerate(pairs, 1):
            if max(before_index, after_index) >= len(images):
                raise IndexError(f"{document_name}: {len(images)} images, requested {before_index}/{after_index}")
            paths = []
            for phase, index in (("before", before_index), ("after", after_index)):
                entry = images[index]
                suffix = Path(entry).suffix.lower()
                filename = f"{group.replace('/', '-')}-{pair_number}-{phase}{suffix}"
                (DEST / filename).write_bytes(archive.read(entry))
                paths.append((f"../../references/documentation-swipe/{filename}", entry))
            reviewed.append({"before": paths[0][0], "after": paths[1][0], "sourceFolder": document.parent.name, "sourceDocument": document_name, "beforeEntry": paths[0][1], "afterEntry": paths[1][1]})
        result["groups"][group] = reviewed
MANIFEST.write_text(json.dumps(result, ensure_ascii=False, indent=2) + "\n", encoding="utf-8")
print(f"Extracted {sum(map(len, result['groups'].values()))} reviewed comparison pairs")
